// <auto-generated />
using System;
using DOAN_LAPTRINHWEB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DOAN_LAPTRINHWEB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260618164226_AddFollowTable")]
    partial class AddFollowTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ReputationRequired")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#6c757d",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 24, 940, DateTimeKind.Utc).AddTicks(2195),
                            Description = "Created your first post",
                            Icon = "file-text",
                            Name = "First Post",
                            ReputationRequired = 0,
                            Type = "milestone"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#ffc107",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 24, 940, DateTimeKind.Utc).AddTicks(2199),
                            Description = "Made 10 posts",
                            Icon = "star",
                            Name = "Active Member",
                            ReputationRequired = 10,
                            Type = "milestone"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#17a2b8",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 24, 940, DateTimeKind.Utc).AddTicks(2201),
                            Description = "Made 50 posts",
                            Icon = "award",
                            Name = "Contributor",
                            ReputationRequired = 50,
                            Type = "milestone"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#28a745",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 24, 940, DateTimeKind.Utc).AddTicks(2202),
                            Description = "Made 100 posts",
                            Icon = "shield",
                            Name = "Veteran",
                            ReputationRequired = 100,
                            Type = "milestone"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#fd7e14",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 24, 940, DateTimeKind.Utc).AddTicks(2203),
                            Description = "Received 10 upvotes",
                            Icon = "thumbs-up",
                            Name = "Helpful",
                            ReputationRequired = 100,
                            Type = "reputation"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#dc3545",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 24, 940, DateTimeKind.Utc).AddTicks(2205),
                            Description = "Received 50 upvotes",
                            Icon = "heart",
                            Name = "Popular",
                            ReputationRequired = 500,
                            Type = "reputation"
                        },
                        new
                        {
                            Id = 7,
                            Color = "#6f42c1",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 24, 940, DateTimeKind.Utc).AddTicks(2206),
                            Description = "Received 100 upvotes",
                            Icon = "crown",
                            Name = "Legendary",
                            ReputationRequired = 1000,
                            Type = "reputation"
                        },
                        new
                        {
                            Id = 8,
                            Color = "#20c997",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 24, 940, DateTimeKind.Utc).AddTicks(2207),
                            Description = "Bookmarked 10 posts",
                            Icon = "bookmark",
                            Name = "Bookworm",
                            ReputationRequired = 0,
                            Type = "special"
                        },
                        new
                        {
                            Id = 9,
                            Color = "#0dcaf0",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 24, 940, DateTimeKind.Utc).AddTicks(2209),
                            Description = "Posted between midnight and 5 AM",
                            Icon = "moon",
                            Name = "Night Owl",
                            ReputationRequired = 0,
                            Type = "special"
                        },
                        new
                        {
                            Id = 10,
                            Color = "#ffc107",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 24, 940, DateTimeKind.Utc).AddTicks(2210),
                            Description = "Reached 100 reputation points",
                            Icon = "trophy",
                            Name = "Century Club",
                            ReputationRequired = 100,
                            Type = "rank"
                        });
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.Bookmark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId", "PostId")
                        .IsUnique();

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PostCount")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#f85149",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 24, 940, DateTimeKind.Utc).AddTicks(1990),
                            CreatedById = 1,
                            Description = "Thảo luận về phương pháp, công cụ và kỹ thuật kiểm thử xâm nhập. Chia sẻ kinh nghiệm từ các bài lab thực tế.",
                            DisplayOrder = 1,
                            Icon = "ti-bug",
                            IsActive = true,
                            Name = "Pentest",
                            PostCount = 0,
                            Slug = "pentest"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#f0883e",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 24, 940, DateTimeKind.Utc).AddTicks(2018),
                            CreatedById = 1,
                            Description = "Phân tích malware tĩnh và động, reverse engineering, nghiên cứu virus và các mối đe dọa mới.",
                            DisplayOrder = 2,
                            Icon = "ti-virus",
                            IsActive = true,
                            Name = "Malware Analysis",
                            PostCount = 0,
                            Slug = "malware"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#388bfd",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 24, 940, DateTimeKind.Utc).AddTicks(2020),
                            CreatedById = 1,
                            Description = "OWASP Top 10, XSS, SQLi, CSRF, LFI/RFI và bảo mật ứng dụng web. Các bài lab và writeup CTF.",
                            DisplayOrder = 3,
                            Icon = "ti-world",
                            IsActive = true,
                            Name = "Web Security",
                            PostCount = 0,
                            Slug = "web-security"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#2ecc71",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 24, 940, DateTimeKind.Utc).AddTicks(2022),
                            CreatedById = 1,
                            Description = "Tường lửa, IDS/IPS, giám sát mạng, giao thức và phân tích lưu lượng. Công cụ Wireshark, Snort.",
                            DisplayOrder = 4,
                            Icon = "ti-network",
                            IsActive = true,
                            Name = "Network Security",
                            PostCount = 0,
                            Slug = "network"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#bc8cff",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 24, 940, DateTimeKind.Utc).AddTicks(2024),
                            CreatedById = 1,
                            Description = "Mã hóa, hash, PKI, chữ ký số và các giao thức mật mã. Bài toán và thách thức crypto.",
                            DisplayOrder = 5,
                            Icon = "ti-lock",
                            IsActive = true,
                            Name = "Cryptography",
                            PostCount = 0,
                            Slug = "crypto"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#00e5a0",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 24, 940, DateTimeKind.Utc).AddTicks(2026),
                            CreatedById = 1,
                            Description = "Trung tâm điều hành bảo mật, phát hiện và ứng phó sự cố, threat hunting và DFIR.",
                            DisplayOrder = 6,
                            Icon = "ti-shield",
                            IsActive = true,
                            Name = "SOC / Blue Team",
                            PostCount = 0,
                            Slug = "soc"
                        },
                        new
                        {
                            Id = 7,
                            Color = "#f39c12",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 24, 940, DateTimeKind.Utc).AddTicks(2028),
                            CreatedById = 1,
                            Description = "Disassembler, decompiler, phân tích binary, unpacking và patching. Công cụ IDA, Ghidra, x64dbg.",
                            DisplayOrder = 7,
                            Icon = "ti-cpu",
                            IsActive = true,
                            Name = "Reverse Engineering",
                            PostCount = 0,
                            Slug = "reverse-engineering"
                        });
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ChatRoomId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PinnedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PinnedById")
                        .HasColumnType("int");

                    b.Property<int?>("ReplyToId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChatRoomId");

                    b.HasIndex("PinnedById");

                    b.HasIndex("ReplyToId");

                    b.HasIndex("SenderId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.ChatMessageReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("MessageId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMessageReactions");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.ChatRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("ChatRooms");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.ChatRoomMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatRoomId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChatRoomId");

                    b.HasIndex("UserId", "ChatRoomId")
                        .IsUnique();

                    b.ToTable("ChatRoomMembers");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DownvoteCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpvoteCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.CommentVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUpvote")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId", "CommentId")
                        .IsUnique();

                    b.ToTable("CommentVotes");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.Follow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FollowerId")
                        .HasColumnType("int");

                    b.Property<int>("FollowingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FollowingId");

                    b.HasIndex("FollowerId", "FollowingId")
                        .IsUnique();

                    b.ToTable("Follows");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActorId")
                        .HasColumnType("int");

                    b.Property<int?>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("RecipientId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("CommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("RecipientId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CommentCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DownvoteCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpvoteCount")
                        .HasColumnType("int");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.PostAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UploadedById");

                    b.ToTable("PostAttachments");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.PostTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("PostTags");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.PostVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUpvote")
                        .HasColumnType("bit");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId", "PostId")
                        .IsUnique();

                    b.ToTable("PostVotes");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.RateLimitRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LastRequest")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestCount")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("WindowStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Endpoint");

                    b.ToTable("RateLimitRecords");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.ReputationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<int?>("ActorId")
                        .HasColumnType("int");

                    b.Property<int?>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PointsChange")
                        .HasColumnType("int");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("RankAfter")
                        .HasColumnType("int");

                    b.Property<int>("TotalPointsAfter")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("CommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("ReputationHistories");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.SecurityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IpAddress");

                    b.HasIndex("UserId");

                    b.ToTable("SecurityLogs");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BanReason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CoverPhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailVerificationToken")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime?>("EmailVerificationTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastLoginIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("ReputationPoints")
                        .HasColumnType("int");

                    b.Property<string>("ResetToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "System Administrator",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 25, 287, DateTimeKind.Utc).AddTicks(2890),
                            DisplayName = "Administrator",
                            Email = "admin@cyberforum.local",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsBanned = false,
                            IsEmailVerified = true,
                            PasswordHash = "$2a$11$srlguoMyimELKrP60I4Q9.PDxHHJOP3g1JXdnewUWPUw2Znq28.Ii",
                            Rank = 5,
                            ReputationPoints = 9999,
                            Role = 2,
                            UpdatedAt = new DateTime(2026, 6, 18, 16, 42, 25, 287, DateTimeKind.Utc).AddTicks(2892),
                            Username = "admin"
                        },
                        new
                        {
                            Id = 101,
                            Bio = "System Administrator",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 25, 287, DateTimeKind.Utc).AddTicks(3020),
                            DisplayName = "Admin 2",
                            Email = "admin2@cyberforum.local",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsBanned = false,
                            IsEmailVerified = true,
                            PasswordHash = "$2a$11$srlguoMyimELKrP60I4Q9.PDxHHJOP3g1JXdnewUWPUw2Znq28.Ii",
                            Rank = 5,
                            ReputationPoints = 5000,
                            Role = 2,
                            UpdatedAt = new DateTime(2026, 6, 18, 16, 42, 25, 287, DateTimeKind.Utc).AddTicks(3020),
                            Username = "admin2"
                        },
                        new
                        {
                            Id = 102,
                            Bio = "System Administrator",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 25, 287, DateTimeKind.Utc).AddTicks(3985),
                            DisplayName = "Admin 3",
                            Email = "admin3@cyberforum.local",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsBanned = false,
                            IsEmailVerified = true,
                            PasswordHash = "$2a$11$srlguoMyimELKrP60I4Q9.PDxHHJOP3g1JXdnewUWPUw2Znq28.Ii",
                            Rank = 5,
                            ReputationPoints = 5000,
                            Role = 2,
                            UpdatedAt = new DateTime(2026, 6, 18, 16, 42, 25, 287, DateTimeKind.Utc).AddTicks(3986),
                            Username = "admin3"
                        },
                        new
                        {
                            Id = 103,
                            Bio = "System Administrator",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 25, 287, DateTimeKind.Utc).AddTicks(4012),
                            DisplayName = "Admin 4",
                            Email = "admin4@cyberforum.local",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsBanned = false,
                            IsEmailVerified = true,
                            PasswordHash = "$2a$11$srlguoMyimELKrP60I4Q9.PDxHHJOP3g1JXdnewUWPUw2Znq28.Ii",
                            Rank = 5,
                            ReputationPoints = 5000,
                            Role = 2,
                            UpdatedAt = new DateTime(2026, 6, 18, 16, 42, 25, 287, DateTimeKind.Utc).AddTicks(4013),
                            Username = "admin4"
                        },
                        new
                        {
                            Id = 104,
                            Bio = "System Administrator",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 25, 287, DateTimeKind.Utc).AddTicks(4028),
                            DisplayName = "Admin 5",
                            Email = "admin5@cyberforum.local",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsBanned = false,
                            IsEmailVerified = true,
                            PasswordHash = "$2a$11$srlguoMyimELKrP60I4Q9.PDxHHJOP3g1JXdnewUWPUw2Znq28.Ii",
                            Rank = 5,
                            ReputationPoints = 5000,
                            Role = 2,
                            UpdatedAt = new DateTime(2026, 6, 18, 16, 42, 25, 287, DateTimeKind.Utc).AddTicks(4028),
                            Username = "admin5"
                        },
                        new
                        {
                            Id = 201,
                            Bio = "Cybersecurity Enthusiast",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 25, 287, DateTimeKind.Utc).AddTicks(4046),
                            DisplayName = "Member 1",
                            Email = "user1@cyberforum.local",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsBanned = false,
                            IsEmailVerified = true,
                            PasswordHash = "$2a$11$koSQ06.rb4TA4Wq0BEoQMONRS3jnVoKiKYHNbsDt5GgWVkPPYijju",
                            Rank = 0,
                            ReputationPoints = 10,
                            Role = 0,
                            UpdatedAt = new DateTime(2026, 6, 18, 16, 42, 25, 287, DateTimeKind.Utc).AddTicks(4046),
                            Username = "user1"
                        },
                        new
                        {
                            Id = 202,
                            Bio = "Cybersecurity Enthusiast",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 25, 287, DateTimeKind.Utc).AddTicks(4057),
                            DisplayName = "Member 2",
                            Email = "user2@cyberforum.local",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsBanned = false,
                            IsEmailVerified = true,
                            PasswordHash = "$2a$11$koSQ06.rb4TA4Wq0BEoQMONRS3jnVoKiKYHNbsDt5GgWVkPPYijju",
                            Rank = 0,
                            ReputationPoints = 20,
                            Role = 0,
                            UpdatedAt = new DateTime(2026, 6, 18, 16, 42, 25, 287, DateTimeKind.Utc).AddTicks(4057),
                            Username = "user2"
                        },
                        new
                        {
                            Id = 203,
                            Bio = "Cybersecurity Enthusiast",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 25, 287, DateTimeKind.Utc).AddTicks(4064),
                            DisplayName = "Member 3",
                            Email = "user3@cyberforum.local",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsBanned = false,
                            IsEmailVerified = true,
                            PasswordHash = "$2a$11$koSQ06.rb4TA4Wq0BEoQMONRS3jnVoKiKYHNbsDt5GgWVkPPYijju",
                            Rank = 0,
                            ReputationPoints = 30,
                            Role = 0,
                            UpdatedAt = new DateTime(2026, 6, 18, 16, 42, 25, 287, DateTimeKind.Utc).AddTicks(4065),
                            Username = "user3"
                        },
                        new
                        {
                            Id = 204,
                            Bio = "Cybersecurity Enthusiast",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 25, 287, DateTimeKind.Utc).AddTicks(4072),
                            DisplayName = "Member 4",
                            Email = "user4@cyberforum.local",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsBanned = false,
                            IsEmailVerified = true,
                            PasswordHash = "$2a$11$koSQ06.rb4TA4Wq0BEoQMONRS3jnVoKiKYHNbsDt5GgWVkPPYijju",
                            Rank = 0,
                            ReputationPoints = 40,
                            Role = 0,
                            UpdatedAt = new DateTime(2026, 6, 18, 16, 42, 25, 287, DateTimeKind.Utc).AddTicks(4072),
                            Username = "user4"
                        },
                        new
                        {
                            Id = 205,
                            Bio = "Cybersecurity Enthusiast",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 25, 287, DateTimeKind.Utc).AddTicks(4171),
                            DisplayName = "Member 5",
                            Email = "user5@cyberforum.local",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsBanned = false,
                            IsEmailVerified = true,
                            PasswordHash = "$2a$11$koSQ06.rb4TA4Wq0BEoQMONRS3jnVoKiKYHNbsDt5GgWVkPPYijju",
                            Rank = 0,
                            ReputationPoints = 50,
                            Role = 0,
                            UpdatedAt = new DateTime(2026, 6, 18, 16, 42, 25, 287, DateTimeKind.Utc).AddTicks(4171),
                            Username = "user5"
                        },
                        new
                        {
                            Id = 206,
                            Bio = "Cybersecurity Enthusiast",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 25, 287, DateTimeKind.Utc).AddTicks(4179),
                            DisplayName = "Member 6",
                            Email = "user6@cyberforum.local",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsBanned = false,
                            IsEmailVerified = true,
                            PasswordHash = "$2a$11$koSQ06.rb4TA4Wq0BEoQMONRS3jnVoKiKYHNbsDt5GgWVkPPYijju",
                            Rank = 0,
                            ReputationPoints = 60,
                            Role = 0,
                            UpdatedAt = new DateTime(2026, 6, 18, 16, 42, 25, 287, DateTimeKind.Utc).AddTicks(4179),
                            Username = "user6"
                        },
                        new
                        {
                            Id = 207,
                            Bio = "Cybersecurity Enthusiast",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 25, 287, DateTimeKind.Utc).AddTicks(4224),
                            DisplayName = "Member 7",
                            Email = "user7@cyberforum.local",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsBanned = false,
                            IsEmailVerified = true,
                            PasswordHash = "$2a$11$koSQ06.rb4TA4Wq0BEoQMONRS3jnVoKiKYHNbsDt5GgWVkPPYijju",
                            Rank = 0,
                            ReputationPoints = 70,
                            Role = 0,
                            UpdatedAt = new DateTime(2026, 6, 18, 16, 42, 25, 287, DateTimeKind.Utc).AddTicks(4225),
                            Username = "user7"
                        },
                        new
                        {
                            Id = 208,
                            Bio = "Cybersecurity Enthusiast",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 25, 287, DateTimeKind.Utc).AddTicks(4232),
                            DisplayName = "Member 8",
                            Email = "user8@cyberforum.local",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsBanned = false,
                            IsEmailVerified = true,
                            PasswordHash = "$2a$11$koSQ06.rb4TA4Wq0BEoQMONRS3jnVoKiKYHNbsDt5GgWVkPPYijju",
                            Rank = 0,
                            ReputationPoints = 80,
                            Role = 0,
                            UpdatedAt = new DateTime(2026, 6, 18, 16, 42, 25, 287, DateTimeKind.Utc).AddTicks(4233),
                            Username = "user8"
                        },
                        new
                        {
                            Id = 209,
                            Bio = "Cybersecurity Enthusiast",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 25, 287, DateTimeKind.Utc).AddTicks(4240),
                            DisplayName = "Member 9",
                            Email = "user9@cyberforum.local",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsBanned = false,
                            IsEmailVerified = true,
                            PasswordHash = "$2a$11$koSQ06.rb4TA4Wq0BEoQMONRS3jnVoKiKYHNbsDt5GgWVkPPYijju",
                            Rank = 0,
                            ReputationPoints = 90,
                            Role = 0,
                            UpdatedAt = new DateTime(2026, 6, 18, 16, 42, 25, 287, DateTimeKind.Utc).AddTicks(4241),
                            Username = "user9"
                        },
                        new
                        {
                            Id = 210,
                            Bio = "Cybersecurity Enthusiast",
                            CreatedAt = new DateTime(2026, 6, 18, 16, 42, 25, 287, DateTimeKind.Utc).AddTicks(4248),
                            DisplayName = "Member 10",
                            Email = "user10@cyberforum.local",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsBanned = false,
                            IsEmailVerified = true,
                            PasswordHash = "$2a$11$koSQ06.rb4TA4Wq0BEoQMONRS3jnVoKiKYHNbsDt5GgWVkPPYijju",
                            Rank = 0,
                            ReputationPoints = 100,
                            Role = 0,
                            UpdatedAt = new DateTime(2026, 6, 18, 16, 42, 25, 287, DateTimeKind.Utc).AddTicks(4253),
                            Username = "user10"
                        });
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.UserBadge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BadgeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.HasIndex("UserId", "BadgeId")
                        .IsUnique();

                    b.ToTable("UserBadges");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.UserUpload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("FileType")
                        .HasColumnType("int");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("UserUploads");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.ActivityLog", b =>
                {
                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.User", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.Bookmark", b =>
                {
                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.User", "User")
                        .WithMany("Bookmarks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.Category", b =>
                {
                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.ChatMessage", b =>
                {
                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.ChatRoom", "ChatRoom")
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.User", "PinnedBy")
                        .WithMany()
                        .HasForeignKey("PinnedById");

                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.ChatMessage", "ReplyTo")
                        .WithMany()
                        .HasForeignKey("ReplyToId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChatRoom");

                    b.Navigation("PinnedBy");

                    b.Navigation("ReplyTo");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.ChatMessageReaction", b =>
                {
                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.ChatMessage", "Message")
                        .WithMany("Reactions")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.ChatRoom", b =>
                {
                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.ChatRoomMember", b =>
                {
                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.ChatRoom", "ChatRoom")
                        .WithMany("Members")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.User", "User")
                        .WithMany("ChatRooms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.Comment", b =>
                {
                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.User", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("ParentComment");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.CommentVote", b =>
                {
                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.Comment", "Comment")
                        .WithMany("Votes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.Follow", b =>
                {
                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.User", "Follower")
                        .WithMany()
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.User", "Following")
                        .WithMany()
                        .HasForeignKey("FollowingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Follower");

                    b.Navigation("Following");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.Notification", b =>
                {
                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Comment");

                    b.Navigation("Post");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.Post", b =>
                {
                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.User", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.PostAttachment", b =>
                {
                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.Post", "Post")
                        .WithMany("Attachments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.PostTag", b =>
                {
                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.Post", "Post")
                        .WithMany("PostTags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.PostVote", b =>
                {
                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.Post", "Post")
                        .WithMany("Votes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.RefreshToken", b =>
                {
                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.ReputationHistory", b =>
                {
                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.User", "Actor")
                        .WithMany("ReputationHistoriesAsActor")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.User", "User")
                        .WithMany("ReputationHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Comment");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.SecurityLog", b =>
                {
                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.User", "User")
                        .WithMany("SecurityLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.UserBadge", b =>
                {
                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.Badge", "Badge")
                        .WithMany()
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.User", "User")
                        .WithMany("Badges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.UserUpload", b =>
                {
                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DOAN_LAPTRINHWEB.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.ChatMessage", b =>
                {
                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.ChatRoom", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.Comment", b =>
                {
                    b.Navigation("Replies");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.Post", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Comments");

                    b.Navigation("PostTags");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("DOAN_LAPTRINHWEB.Models.Entities.User", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Badges");

                    b.Navigation("Bookmarks");

                    b.Navigation("ChatRooms");

                    b.Navigation("Comments");

                    b.Navigation("Posts");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ReputationHistories");

                    b.Navigation("ReputationHistoriesAsActor");

                    b.Navigation("SecurityLogs");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
